global:
  scrape_interval: 2s

rule_files:
  - "alertmanager.yml"

scrape_configs: 
  - job_name: 'service_discovery'
    scrape_interval: 10s
    file_sd_configs:
    - refresh_interval: 10s
      files:
      - /etc/prometheus/service_discovery.yml

        

