{
 "title": "Monitoring dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Service latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exporter_0_network_service_latency",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Memory active file kb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_sys_memory_Active_file_kb",
     "legendFormat": "Memory active files"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesIn[10m])",
     "legendFormat": "Byte In"
    },
    {
     "expr": "rate(mongodb_ss_network_bytesOut[10m])",
     "legendFormat": "Byte Out"
    }
   ]
  },
  {
   "title": "Up Time in minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_ss_uptime/60" }
   ]
  },
  {
   "title": "Current connection",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\"}"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"insert\"}[10m])",
     "legendFormat": "insert"
    },
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"delete\"}[10m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type=\"update\"}[10m])",
     "legendFormat": "update"
    }
   ]
  },
  {
   "title": "Percentage of service NOT reachable",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_0_http_failure_request_total/exporter_0_http_total_request_total*100"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_queryExecutor_scanned[10m])"
    }
   ]
  }
 ]
}